apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: keycloak
data:
  k8s-stack-realm.json: |
    {
      "realm": "k8s-stack",
      "displayName": "K8s Stack Realm",
      "enabled": true,
      "registrationAllowed": false,
      "registrationEmailAsUsername": false,
      "rememberMe": true,
      "verifyEmail": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 30,
      "roles": {
        "realm": [
          {
            "name": "admin",
            "description": "Administrator role for all services"
          },
          {
            "name": "developer",
            "description": "Developer role with limited access"
          },
          {
            "name": "viewer",
            "description": "Read-only access role"
          }
        ]
      },
      "groups": [
        {
          "name": "jenkins-admins",
          "path": "/jenkins-admins",
          "realmRoles": ["admin"]
        },
        {
          "name": "jenkins-developers",
          "path": "/jenkins-developers",
          "realmRoles": ["developer"]
        },
        {
          "name": "jenkins-viewers",
          "path": "/jenkins-viewers",
          "realmRoles": ["viewer"]
        },
        {
          "name": "n8n-admins",
          "path": "/n8n-admins",
          "realmRoles": ["admin"]
        },
        {
          "name": "postgres-admins",
          "path": "/postgres-admins",
          "realmRoles": ["admin"]
        }
      ],
      "users": [
        {
          "username": "jmiguelmangas",
          "email": "jmiguelmangas@example.com",
          "firstName": "Jose Miguel",
          "lastName": "Mangas",
          "enabled": true,
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "leicakanon2025",
              "temporary": false
            }
          ],
          "realmRoles": ["admin"],
          "groups": [
            "/jenkins-admins",
            "/n8n-admins",
            "/postgres-admins"
          ]
        }
      ],
      "clients": [
        {
          "clientId": "jenkins",
          "name": "Jenkins CI/CD",
          "description": "Jenkins continuous integration server",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "jenkins-secret",
          "redirectUris": [
            "http://jenkins.local:8080/securityRealm/finishLogin",
            "http://localhost:8081/securityRealm/finishLogin"
          ],
          "webOrigins": [
            "http://jenkins.local:8080",
            "http://localhost:8081"
          ],
          "protocol": "openid-connect",
          "attributes": {
            "saml.assertion.signature": "false",
            "saml.multivalued.roles": "false",
            "saml.force.post.binding": "false",
            "saml.encrypt": "false",
            "saml.server.signature": "false",
            "saml.server.signature.keyinfo.ext": "false",
            "exclude.session.state.from.auth.response": "false",
            "saml_force_name_id_format": "false",
            "saml.client.signature": "false",
            "tls.client.certificate.bound.access.tokens": "false",
            "saml.authnstatement": "false",
            "display.on.consent.screen": "false",
            "saml.onetimeuse.condition": "false"
          },
          "authenticationFlowBindingOverrides": {},
          "fullScopeAllowed": true,
          "nodeReRegistrationTimeout": -1,
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ],
          "defaultClientScopes": [
            "web-origins",
            "role_list",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        },
        {
          "clientId": "n8n",
          "name": "N8N Workflow Automation",
          "description": "N8N workflow automation platform",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "n8n-secret",
          "redirectUris": [
            "http://n8n.local:5678/oauth/callback",
            "http://localhost:5678/oauth/callback"
          ],
          "webOrigins": [
            "http://n8n.local:5678",
            "http://localhost:5678"
          ],
          "protocol": "openid-connect",
          "fullScopeAllowed": true,
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        },
        {
          "clientId": "postgres-admin",
          "name": "PostgreSQL Admin Interface",
          "description": "PostgreSQL administration interface",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "postgres-secret",
          "redirectUris": [
            "http://pgadmin.local:5050/oauth/callback",
            "http://localhost:5050/oauth/callback"
          ],
          "webOrigins": [
            "http://pgadmin.local:5050",
            "http://localhost:5050"
          ],
          "protocol": "openid-connect",
          "fullScopeAllowed": true
        }
      ]
    }
